server:
  port: 8574

springdoc:
  show-actuator: true
  swagger-ui:
    filter: true
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: ${KEYCLOAK_SWAGGER_AUTH_CLIENT_ID}
      tokenUrl: "http://localhost:8080/realms/schenectady/protocol/openid-connect/token"
      authorizationUrl: "http://localhost:8080/realms/schenectady/protocol/openid-connect/auth"

com.c4-soft.springaddons.oidc:
  ops:
    - iss: http://localhost:8080
      username-claim: preferred_username
      authorities:
        - path: $.realm_access.roles
        - path: $.resource_access.*.roles
  resource-server:
    permit-all:
      - "/v3/api-docs/**"
      - "/swagger-ui/**"
      - "/swagger-ui.html"
    cors:
      - path: /**
        allowed-origin-patterns: http://localhost:4200