server:
  port: 8574

springdoc:
  show-actuator: true
  swagger-ui:
    filter: true
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: ${KEYCLOAK_SWAGGER_AUTH_CLIENT_ID}
      tokenUrl: "http://localhost:8080/realms/schenectady/protocol/openid-connect/token"
      authorizationUrl: "http://localhost:8080/realms/schenectady/protocol/openid-connect/auth"

scheme: http
origins: ${scheme}://localhost:4200
keycloak-port: 8080

com.c4-soft.springaddons.oidc:
  ops:
    - iss: ${scheme}://localhost:${keycloak-port}
      username-claim: preferred_username
      authorities:
        - path: $.realm_access.roles
        - path: $.resource_access.*.roles
  resourceserver:
    permit-all:
      - "/v3/api-docs/**"
      - "/swagger-ui/**"
    cors:
      - path: /**
        allowed-origin-patterns: ${origins}